spring:
  main:
    web-application-type: none
    lazy-initialization: true
  datasource:
    platform: h2
    url: jdbc:h2:./app/database;DB_CLOSE_ON_EXIT=TRUE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: vladik
    password: password
  jpa:
    database: default
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
      path: /h2
      settings:
        trace: false
        web-allow-others: true
  gson:
    pretty-printing: true